package org.example.model;

import com.fasterxml.jackson.annotation.JsonBackReference;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.time.LocalDate;

@Entity
@Table(name = "reports")
public class Report {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @NotNull(message = "Report date is required")
    private LocalDate reportDate;
    @NotBlank(message = "Generated by is required")
    private String generatedBy;
    @NotBlank(message = "File path is required")
    private String filePath;
    @NotBlank(message = "Type is required")
    private String type; // e.g., DAILY, WEEKLY
    @NotNull(message = "Patient is required")
    @ManyToOne
    @JoinColumn(name = "patient_id")
    @JsonBackReference
    private Patient patient;
    @NotNull(message = "Appointment is required")
    @ManyToOne
    @JoinColumn(name = "appointment_id")
    @JsonBackReference
    private Appointment appointment;
    // getters and setters


    public Long getId() {
        return id;
    }

    public LocalDate getReportDate() {
        return reportDate;
    }

    public String getGeneratedBy() {
        return generatedBy;
    }

    public String getFilePath() {
        return filePath;
    }

    public String getType() {
        return type;
    }

    public Patient getPatient() {
        return patient;
    }

    public Appointment getAppointment() {
        return appointment;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void setReportDate(LocalDate reportDate) {
        this.reportDate = reportDate;
    }

    public void setGeneratedBy(String generatedBy) {
        this.generatedBy = generatedBy;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public void setType(String type) {
        this.type = type;
    }

    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    public void setAppointment(Appointment appointment) {
        this.appointment = appointment;
    }
}
